options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_MEDIUM'

steps:
  # Paso 1: Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/davivienda-reclamos/despliegue/ocr-emergia:${_COMMIT_SHA}'
      - '.'

  # Paso 2: Empujar la imagen al Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/davivienda-reclamos/despliegue/ocr-emergia:${_COMMIT_SHA}'

  # Paso 3: Desplegar a Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'davivienda-causa-raiz-v2'
      - '--image'
      - 'us-central1-docker.pkg.dev/davivienda-reclamos/despliegue/ocr-emergia:${_COMMIT_SHA}'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'  
      - '--cpu'
      - '1'
      - '--concurrency'
      - '30'
      - '--max-instances'
      - '2'
      - '--timeout'
      - '600'
      - '--port'
      - '8082'

images:
  - 'us-central1-docker.pkg.dev/davivienda-reclamos/despliegue/ocr-emergia:${_COMMIT_SHA}'

substitutions:
  _COMMIT_SHA: "${COMMIT_SHA}"